package se.chalmers.dat255.group22.escape.fragments;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import se.chalmers.dat255.group22.escape.NewBlockActivity;
import se.chalmers.dat255.group22.escape.R;
import se.chalmers.dat255.group22.escape.adapters.BlockListAdapter;
import se.chalmers.dat255.group22.escape.database.DBHandler;
import se.chalmers.dat255.group22.escape.objects.IBlockObject;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.ListFragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.Button;
import android.widget.ListView;

/**
 * Class representing the fragment that's listing all autogenerated blocks and
 * provides a button for autogenerating new blocks.
 * 
 * @author Simon Persson
 */
public class BlocksFragment extends ListFragment implements OnClickListener {
	
	private final List<String> list = new ArrayList<String>();

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		
		View view = inflater
				.inflate(R.layout.blocks_fragment, container, false);
		
		ListView lview = (ListView) view.findViewById(R.id.blocks_list);
		
		final DBHandler dBHandler = new DBHandler(view.getContext());
		List<IBlockObject> blocks = dBHandler.getAllBlocks();
		final Map<String, IBlockObject> blockDescriptions = new HashMap<String, IBlockObject>();
		for (IBlockObject block : blocks) {
			blockDescriptions.put(block.getName() + ": " + block.getHours()
					+ "h total, " + block.getSessionMinutes()
					+ " min each session", block);
		}
		
		for (String listData : blockDescriptions.keySet()) {
			if (!list.contains(listData)) {
				list.add(listData);
			}
		}
		
		final BlockListAdapter adapter = new BlockListAdapter(lview.getContext(), 
				android.R.layout.simple_list_item_1, list);
		lview.setAdapter(adapter);

		lview.setOnItemClickListener(new OnItemClickListener() {

			@Override
			public void onItemClick(AdapterView<?> parent, final View view,
			          int position, long id) {
				
				final String item = (String) parent.getItemAtPosition(position);
				dBHandler.deleteBlock(blockDescriptions.get(item));
				blockDescriptions.remove(item);
				list.remove(item);
				adapter.notifyDataSetChanged();
				view.setAlpha(1);
			}
		});
		
		dBHandler.close();
		return view;
	}

	@Override
	public void onViewCreated(View view, Bundle savedInstanceState) {
		
		Button newBlockButton = (Button) getActivity().findViewById(
				R.id.new_block_button);
		newBlockButton.setOnClickListener(this);
	}

	@Override
	public void onClick(View v) {
		Intent intent = new Intent(getActivity(), NewBlockActivity.class);
		startActivity(intent);
	}
}
